builds:
  - main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
brews:
  - name: kubectl-auth0
    tap:
      owner: KMConner
      name: homebrew-tap
    description: "Sign in k8s cluster using auth0"
    homepage: "https://github.com/KMConner/kubectl-auth0"
    folder: Formula
